#ifndef _AUDIO_H
#define _AUDIO_H

#define SAMPLE_RATE 48000
#define CONTROL_RATE 1500
#define BLOCK_SIZE (SAMPLE_RATE / CONTROL_RATE)

#if BLOCK_SIZE * CONTROL_RATE != SAMPLE_RATE
#error "SR-CR relation is odd"
#endif

#define REPEAT2(SOME) SOME SOME
#define REPEAT4(SOME) REPEAT2(SOME) REPEAT2(SOME)
#define REPEAT8(SOME) REPEAT4(SOME) REPEAT4(SOME)
#define REPEAT16(SOME) REPEAT8(SOME) REPEAT8(SOME)
#define REPEAT32(SOME) REPEAT16(SOME) REPEAT16(SOME)
#define REPEAT64(SOME) REPEAT32(SOME) REPEAT32(SOME)
#define REPEAT128(SOME) REPEAT64(SOME) REPEAT64(SOME)
#define REPEAT256(SOME) REPEAT128(SOME) REPEAT128(SOME)

#if BLOCK_SIZE == 32
#define REPEAT REPEAT32
#else
#error "please, change repeat block"
#endif

#endif // _AUDIO_H